$ANSIBLE_VAULT;1.1;AES256
39373930613063636539386232623365643333383739633964313031643339616133313130313663
3232356137643764623138623163353838346436373232610a323935393765306563396665663064
34636664326234613839633436616339656138623330363935636462333330326663363338343534
3563663435613364380a343236643039396364346537326637643435373266356531396261623764
35646562666239343636396639376633626462343665623837333333366466626137393833666339
37343961623563636534366333366531666639353938646139613434373739343565663638396133
33613163663565326364626261346466356331386333376531663739613864383838623436303439
64303932633334666236633364613363643465643963376337356563646563363339373530383764
62613061346661643436323434393466616335393938316163366630396332393233343537646133
31326436353337613165303661303538626636636364323930376233366632343932393433323932
31323332396337346236323531386463666562633937353534346362373962303135313537306230
39653430363533336162306261333430396361366134366639336239356266363766346530356563
38616163623631626632643339623536386237333830373230633839316335323065356366666664
34333436613363383734623265306163353765303465623964396430396466393739353537366231
35656539396165616430333564356562383562633066666530666366343934633635356237373134
66383739353165363561326636313162373839343137653762393234313765326537306138393965
63373933326337663636393261656333663861636164643635653062366339356266313364626136
30363162303731343232646238616165366234346535646530383230323038643438643136653964
64393963363132363563333335326230333432303066626230383066613330633062313964633630
62346665333233336635656263343130343631306165646264626438353465376130353534386563
31306361636363316162333139613764386233303465353462393037623632333639626137643763
66356531626337393639623339636139353762306632303438613030306532646161363438663162
39333638376235336139343836623430636239373738376636343432363361643334383731343763
35623436356533623035333762363762313238376335316631613330643939656330363762343866
37656136363963646433643638306663383531656136656336636261613463303230333434646536
65306138353765393135356336613131343730373235303064663839333634633566343833343166
65653163363961333439366338626534363037613865666336303065373632313236366361326463
63636532373738323538316135363030616332373663323238333835373763373735626538366430
65656633663463353833333834663238363639333332393937626630663436366535666433303264
33333037353130636562323336643362303965613732303130333666323830316630656231616434
32353662336563366531633661383031663733336463306131343734366162396330626264363665
33373461613932316136356631646232386234666164326530666536366662656339383066363634
31373731393664346361353137653537306165643934666330653232653166393337
